const HangmanWords = [
    { word: "apple", hint: "A popular red or green fruit" },
    { word: "banana", hint: "A long, yellow fruit" },
    { word: "orange", hint: "A citrus fruit and a color" },
    { word: "giraffe", hint: "Tallest land animal" },
    { word: "elephant", hint: "Largest land mammal" },
    { word: "penguin", hint: "A flightless bird that swims" },
    { word: "dolphin", hint: "An intelligent marine mammal" },
    { word: "octopus", hint: "Has eight arms and lives in the ocean" },
    { word: "cheetah", hint: "The fastest land animal" },
    { word: "kangaroo", hint: "An Australian animal that hops" },
    { word: "airplane", hint: "A flying vehicle" },
    { word: "bicycle", hint: "A two-wheeled vehicle powered by pedaling" },
    { word: "submarine", hint: "A watercraft that travels underwater" },
    { word: "satellite", hint: "Orbits planets and aids communication" },
    { word: "helicopter", hint: "An aircraft with rotating blades" },
    { word: "pyramid", hint: "A triangular ancient structure in Egypt" },
    { word: "volcano", hint: "Erupts lava and ash" },
    { word: "galaxy", hint: "A system of stars, planets, and dust" },
    { word: "tornado", hint: "A powerful rotating windstorm" },
    { word: "tsunami", hint: "A large ocean wave caused by an earthquake" },
    { word: "rainbow", hint: "A colorful arc in the sky after rain" },
    { word: "thunder", hint: "A loud sound after lightning" },
    { word: "sunrise", hint: "The start of a new day" },
    { word: "midnight", hint: "The middle of the night" },
    { word: "diamond", hint: "A precious gemstone, often used in rings" },
    { word: "sapphire", hint: "A blue-colored gemstone" },
    { word: "emerald", hint: "A green-colored gemstone" },
    { word: "guitar", hint: "A musical instrument with strings" },
    { word: "piano", hint: "A large instrument with black and white keys" },
    { word: "trumpet", hint: "A brass instrument played by blowing" },
    { word: "violin", hint: "A string instrument played with a bow" },
    { word: "flute", hint: "A wind instrument held horizontally" },
    { word: "chocolate", hint: "A sweet treat made from cocoa" },
    { word: "popcorn", hint: "A snack often eaten at the movies" },
    { word: "pancake", hint: "A flat breakfast food often with syrup" },
    { word: "sandwich", hint: "Two slices of bread with filling" },
    { word: "spaghetti", hint: "A popular Italian pasta dish" },
    { word: "robot", hint: "A machine that can perform tasks" },
    { word: "computer", hint: "An electronic device for processing data" },
    { word: "internet", hint: "A global network connecting computers" },
    { word: "keyboard", hint: "Used to type on a computer" },
    { word: "headphones", hint: "Worn over ears to listen to sound" },
    { word: "basketball", hint: "A sport played with a hoop and ball" },
    { word: "football", hint: "A sport played with an oval ball" },
    { word: "chess", hint: "A strategic board game with pieces" },
    { word: "puzzle", hint: "A game that requires solving problems" },
    { word: "circus", hint: "A show with acrobats and clowns" },
    { word: "zoo", hint: "A place where animals are displayed" },
    { word: "museum", hint: "A place showcasing historical artifacts" },
    { word: "library", hint: "A place filled with books" },
    { word: "garden", hint: "A place with plants and flowers" },
    { word: "island", hint: "Land surrounded by water" },
    { word: "desert", hint: "A dry area with little rainfall" },
    { word: "ocean", hint: "A vast body of saltwater" },
    { word: "jungle", hint: "A dense forest with wild animals" },
    { word: "mountain", hint: "A high landform rising above the earth" },
    { word: "river", hint: "A flowing body of freshwater" },
    { word: "castle", hint: "A large fortified building from the past" },
    { word: "palace", hint: "A grand residence for royalty" },
    { word: "bridge", hint: "A structure that connects two places" },
    { word: "lighthouse", hint: "A tower that guides ships with light" },
    { word: "firefighter", hint: "A person who fights fires" },
    { word: "astronaut", hint: "A person who travels to space" },
    { word: "scientist", hint: "A person who conducts experiments" },
    { word: "teacher", hint: "A person who educates students" },
    { word: "doctor", hint: "A person who treats sick people" },
    { word: "detective", hint: "A person who solves mysteries" },
    { word: "artist", hint: "A person who creates paintings" },
    { word: "author", hint: "A person who writes books" },
    { word: "farmer", hint: "A person who grows crops" },
    { word: "carpenter", hint: "A person who works with wood" },
    { word: "singer", hint: "A person who performs songs" },
    { word: "actor", hint: "A person who performs in movies" },
    { word: "pilot", hint: "A person who flies an airplane" },
    { word: "chef", hint: "A person who cooks professionally" },
    { word: "magician", hint: "A person who performs tricks" },
    { word: "dragon", hint: "A mythical fire-breathing creature" },
    { word: "unicorn", hint: "A horse with a magical horn" },
    { word: "wizard", hint: "A person who uses magic" },
    { word: "vampire", hint: "A creature that drinks blood" },
    { word: "ghost", hint: "A spirit of a dead person" },
    { word: "zombie", hint: "A reanimated undead creature" },
    { word: "mermaid", hint: "A half-human, half-fish creature" },
    { word: "knight", hint: "A warrior in armor from the past" },
    { word: "samurai", hint: "A warrior from ancient Japan" },
    { word: "pirate", hint: "A person who sails and steals" },
    { word: "ninja", hint: "A stealthy Japanese warrior" },
    { word: "robot", hint: "A mechanical device that moves" },
    { word: "alien", hint: "A creature from another planet" },
    { word: "spaceship", hint: "A vehicle used to travel in space" }
];

