const HangmanWords = [
    { word: "quartz", hint: "A hard mineral often used in watches" },
    { word: "fjord", hint: "A narrow inlet between steep cliffs" },
    { word: "cryptic", hint: "Having a mysterious or hidden meaning" },
    { word: "zephyr", hint: "A soft, gentle breeze" },
    { word: "glyph", hint: "A carved or inscribed symbol" },
    { word: "harpoon", hint: "A spear-like weapon for hunting large fish" },
    { word: "labyrinth", hint: "A complex maze" },
    { word: "phantom", hint: "A ghost or illusion" },
    { word: "paradox", hint: "A statement that contradicts itself" },
    { word: "vortex", hint: "A whirling mass of fluid or air" },
    { word: "alchemy", hint: "A medieval practice to turn metals into gold" },
    { word: "chimera", hint: "A mythical creature with parts from different animals" },
    { word: "serpent", hint: "A large snake" },
    { word: "raptor", hint: "A bird of prey" },
    { word: "obsidian", hint: "Volcanic glass formed from lava" },
    { word: "galleon", hint: "A large sailing ship from the 16th–18th centuries" },
    { word: "catacomb", hint: "Underground burial chamber" },
    { word: "plasma", hint: "The fourth state of matter" },
    { word: "mirage", hint: "An optical illusion in the desert" },
    { word: "megalith", hint: "A large prehistoric stone monument" },
    { word: "stalactite", hint: "A hanging mineral formation in caves" },
    { word: "catalyst", hint: "A substance that speeds up a chemical reaction" },
    { word: "maelstrom", hint: "A powerful whirlpool" },
    { word: "hieroglyph", hint: "An ancient Egyptian symbol" },
    { word: "sphinx", hint: "A mythical creature with a lion's body and human head" },
    { word: "cobalt", hint: "A metallic chemical element" },
    { word: "topaz", hint: "A yellow or blue gemstone" },
    { word: "onyx", hint: "A black gemstone" },
    { word: "gargoyle", hint: "A carved stone figure on buildings" },
    { word: "zodiac", hint: "Astrological sign system" },
    { word: "runestone", hint: "A stone carved with ancient letters" },
    { word: "nebula", hint: "A cloud of gas and dust in space" },
    { word: "asteroid", hint: "A small rocky body in space" },
    { word: "eclipse", hint: "When one celestial body blocks another" },
    { word: "equator", hint: "The imaginary line around Earth's middle" },
    { word: "monolith", hint: "A large single upright stone" },
    { word: "fathom", hint: "A unit for measuring water depth" },
    { word: "kelp", hint: "A large brown seaweed" },
    { word: "trident", hint: "A three-pronged spear" },
    { word: "havoc", hint: "Widespread destruction" },
    { word: "mantis", hint: "A predatory insect with folded forearms" },
    { word: "silhouette", hint: "A dark outline of a shape" },
    { word: "trekking", hint: "A long, challenging journey" },
    { word: "citadel", hint: "A fortress protecting a city" },
    { word: "embargo", hint: "A government ban on trade" },
    { word: "relic", hint: "An object from the past" },
    { word: "artifact", hint: "An item made by humans, often historic" },
    { word: "gauntlet", hint: "A protective glove or a challenge" },
    { word: "quiver", hint: "A container for holding arrows" } 
];
